# Generated by Django 4.1.3 on 2022-12-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_avatar_portada_delete_actor_delete_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.DeleteModel(
            name='Portada',
        ),
    ]
