# Generated by Django 4.1.3 on 2022-12-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_blog_imagen_delete_portada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
