# Generated by Django 4.1.3 on 2022-12-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUserManagement', '0002_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='pagina',
            new_name='link',
        ),
    ]
